### ISSUE TITLE
Meet the team

### ISSUE THREAD

**Issue by ld-cd** [NHHSBotball/nhhsbotball.github.io#1]
I would like to add a meet the team page with a little profile of everyone on our team. Aaron this seems to be your child (the website), do you mind if I add one?

**Comment by atomicproton** [comment]
we have one already .-.
http://nohobotball.org/team

**Comment by ld-cd** [comment]
oh how did i miss that, okay i think it might be a good idea to add photos, and finish it.

**Comment by aopell** [comment]
You probably missed it since you can't see it from any other page since it isn't finished
